---
- name: Check boot cmdline paths
  ansible.builtin.stat:
    path: "{{ item }}"
  loop:
    - /boot/cmdline.txt
    - /boot/firmware/cmdline.txt
  register: raspi_config_cmdline_paths

- name: Enable container features in cmdline file
  ansible.builtin.replace:
    path: "{{ item.0.stat.path }}"
    regexp: '^([\w](?!.*\b{{ item.1 }}\b).*)$'
    replace: '\1 {{ item.1 }}'
  loop: "{{ raspi_config_cmdline_paths.results | product(raspi_config_cmdline_containers) | list }}"
  when: item.0.stat.exists
  notify: reboot
