---
- name: ensure utility present
  ansible.builtin.apt:
    name: sshpass
    state: present

- name: check for login
  ansible.builtin.command: |
    sshpass -p {{ raspi_config_auth_test_password }} ssh {{ raspi_config_auth_test_username }}@localhost \
            -o NoHostAuthenticationForLocalhost=yes "echo {{ raspi_config_auth_test_string }}"
  register: auth_test
  changed_when: false
  failed_when: false

- name: optional warning
  ansible.builtin.debug:
    msg: "{{ raspi_config_auth_test_fail_msg }}"
  when: raspi_config_auth_test_string == auth_test.stdout
  # for highlighting purposes
  changed_when: raspi_config_auth_test_string == auth_test.stdout
  failed_when:
    - raspi_config_fail_on_auth_test
    - raspi_config_replace_user['name'] is not none

- name: additional info
  ansible.builtin.debug:
    msg: "{{ raspi_config_auth_test_replace_info }}"
  when:
    - raspi_config_auth_test_string == auth_test.stdout
    - raspi_config_replace_user['name'] is not none
