---
- name: Populate service facts
  service_facts:

- name: Ensure NTP package is installed.
  package:
    name: ntp
    state: present

- name: Ensure tzdata package is installed (Linux).
  package:
    name: tzdata
    state: present
  when: ansible_system == "Linux"

- name: Ensure NTP is running and enabled as configured.
  service:
    name: ntp
    state: started
    enabled: true
  when: raspi_config_ntp_server_enabled | bool

- name: Generate ntp configuration file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    mode: 0644
  notify: restart ntp

- name: Flush all Handlers
  meta: flush_handlers
